apiVersion: v1
data:
  dextr_pascal_sbd.sh: |-
    #!/bin/bash

    wget https://github.com/jsbroks/dextr-keras/releases/download/v1.0.0/dextr_pascal-sbd.h5
  mask_coco_model.sh: |-
    #!/bin/bash

    # Download matterport mask_rcnn_coco model
    wget https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: webserver
  name: webserver-cm1
