apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/coco-annotator-cocoannotator: "true"
        io.kompose.service: workers
    spec:
      containers:
        - image: keyofspectator/default:coco-annotator-workers-stable-20240801
          name: annotator-workers
          volumeMounts:
            - mountPath: /datasets
              name: datasets
      restartPolicy: Always
      volumes:
        - name: datasets
          hostPath:
            path: /datasets
            type: DirectoryOrCreate
